### ISSUE TITLE
not connection issue in homeassistant

### ISSUE THREAD

**Issue by ashobgame** [lwestenberg/homeassistant_bold#2] opened 2022-03-09 20:01 UTC
This error originated from a custom integration.

Logger: custom_components.bold.coordinator
Source: custom_components/bold/coordinator.py:87
Integration: Bold
First occurred: 7:35:11 PM (2 occurrences)
Last logged: 7:35:25 PM

Cannot connect

**Comment by lwestenberg** [comment] 2022-03-09 22:46
Thanks for reporting, looks like something changed in the API and I'm able to reproduce the issue. I'm looking into it.

**Comment by lwestenberg** [comment] 2022-04-02 19:01
Seems that Bold is also having issues. Turn off Bluetooth on your phone and try remote activation with the Bold app. It gives a timeout. I checked the latest app and all server calls still seem to be the same (with X-Auth-Token). I contacted Bold about the issue.

**Comment by michelmolleman** [comment] 2022-09-02 06:57
Is there a solution available. I have the same problem …

**Comment by lwestenberg** [comment] 2022-10-27 19:28
We're working on releasing an official HA integration and have arranged everything officially now with Bold. For now I will close this issue, please check the Core repo on my GitHub to see the latest progress before merging.

**Closed** 2022-10-27 19:28 UTC

**Comment by Gnol86** [comment] 2022-12-06 15:45
Thanks you for the job. Do you have an estimate of when the official integration will be released?

**Comment by lwestenberg** [comment] 2023-01-21 21:11
it can be used as custom_component now from this repo source.

**Comment by peetersit** [comment] 2023-01-22 08:45
It worked right away. Without hassle. This is awesome!!! Keep up the good work…Thanks Patrick
